### ISSUE TITLE
panic: interface conversion: error is jsonschema.InvalidJSONTypeError, not *jsonschema.ValidationError

### ISSUE THREAD

**Issue by gnuletik** [daveshanley/vacuum#271]
Since the [v0.1.0](https://github.com/daveshanley/vacuum/releases/tag/v0.1.0) release, we have the following error when running vacuum on our openapi.yaml files:

```
██    ██  █████   ██████ ██    ██ ██    ██ ███    ███ 
██    ██ ██   ██ ██      ██    ██ ██    ██ ████  ████ 
██    ██ ███████ ██      ██    ██ ██    ██ ██ ████ ██ 
 ██  ██  ██   ██ ██      ██    ██ ██    ██ ██  ██  ██ 
  ████   ██   ██  ██████  ██████   ██████  ██      ██ 


version: latest | compiled: 2023-05-15 08:37:05 UTC
🔗 https://quobix.com/vacuum | https://github.com/daveshanley/vacuum


 INFO  Linting against 42 rules: https://quobix.com/vacuum/rulesets/recommended
panic: interface conversion: error is jsonschema.InvalidJSONTypeError, not *jsonschema.ValidationError

goroutine 93 [running]:
github.com/pb33f/libopenapi-validator/schema_validation.ValidateOpenAPIDocument({0x13e2bd0?, 0xc0003a1140?})
	/home/runner/.cache/pre-commit/reporhok6jmd/golangenv-system/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.5/schema_validation/validate_document.go:32 +0x6b4
github.com/daveshanley/vacuum/functions/openapi.OASSchema.RunRule({}, {0xc0000b2140?, 0x10b6940?, 0x1?}, {0xc00015a660, 0xc00037aa50, {0x10b25c0, 0x13d7b50}, {0x0, 0x0}, ...})
	/home/runner/.cache/pre-commit/reporhok6jmd/functions/openapi/oas_schema.go:48 +0xc5
github.com/daveshanley/vacuum/motor.buildResults({0xc00037aa50, 0xc0003f72c0, {0x13dd270, 0xc000335df0}, 0xc0000b16e0, 0xc000376fe0, 0xc000012870, 0xc00020ea00, 0xc00036fb80, 0x0, ...}, ...)
	/home/runner/.cache/pre-commit/reporhok6jmd/motor/rule_applicator.go:390 +0x64b
github.com/daveshanley/vacuum/motor.runRule({0xc00037aa50, 0xc0003f72c0, {0x13dd270, 0xc000335df0}, 0xc0000b16e0, 0xc000376fe0, 0xc000012870, 0xc00020ea00, 0xc00036fb80, 0x0, ...})
	/home/runner/.cache/pre-commit/reporhok6jmd/motor/rule_applicator.go:314 +0x3af
created by github.com/daveshanley/vacuum/motor.ApplyRulesToRuleSet
	/home/runner/.cache/pre-commit/reporhok6jmd/motor/rule_applicator.go:245 +0xd65
```

This was run with [v0.1.1](https://github.com/daveshanley/vacuum/releases/tag/v0.1.1).

It seems that the error comes from https://github.com/pb33f/libopenapi-validator/blob/2aa624534cada2aa059f54baa27258097ed82a41/schema_validation/validate_schema.go#L75

Should I open an issue there?

Thanks!

**Comment by daveshanley** [comment]
Oh, interesting, this is a bug for sure. will fix asap.

**Comment by daveshanley** [comment]
Can you try `v0.1.3`?

**Comment by daveshanley** [comment]
Oh dear, this is the same thing, just in another part of the validator, doing a whole doc validation vs a single schema. my bad, an oversight on my part.

**Comment by gnuletik** [comment]
Oh good catch!
No worries! Thanks for the feedback!

**Comment by daveshanley** [comment]
Hopefully this is now resolved in vacuum `v0.1.4`

**Comment by gnuletik** [comment]
It works like a charm! Thanks a lot 🚀
