### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kallioaleksi** [daveshanley/vacuum#311]
I'm getting the following error on my spec when trying to lint. Is this an issue in the YAML or in Vacuum?

Installed via `brew` on a MacBook Pro, M1 Pro.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x258 pc=0x10446d198]

goroutine 294 [running]:
github.com/pb33f/libopenapi/datamodel/high/base.(*Schema).MarshalYAMLInline(0x1400068b201?)
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.9.2/datamodel/high/base/schema.go:486 +0x18
github.com/pb33f/libopenapi/datamodel/high/base.(*Schema).RenderInline(0x104ba9a20?)
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.9.2/datamodel/high/base/schema.go:475 +0x1c
github.com/pb33f/libopenapi-validator/schema_validation.validateSchema(0x0, {0x0, 0x0, 0x0}, {0x104bbc820, 0x140001e49c0})
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.8/schema_validation/validate_schema.go:62 +0x80
github.com/pb33f/libopenapi-validator/schema_validation.(*schemaValidator).ValidateSchemaObject(0x14000530ca0?, 0x1d?, {0x104bbc820?, 0x140001e49c0?})
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.8/schema_validation/validate_schema.go:50 +0x3c
github.com/daveshanley/vacuum/parser.ValidateNodeAgainstSchema(0x14000758000?, 0x1400068bc28?, 0x28?)
	/home/runner/work/vacuum/vacuum/parser/json_schema.go:222 +0x254
github.com/daveshanley/vacuum/functions/openapi.analyzeExample({0x140004006f0, 0x10}, 0x140001608c0, {0x14000296400, 0x1f}, 0x14000758000?, {0x140003d0030, 0x14000321600, {0x104b85e40, 0x104c815d8}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:510 +0xea0
github.com/daveshanley/vacuum/functions/openapi.checkExamples(0x14000160500, {0x14000296400, 0x1f}, 0x0?, {0x140003d0030, 0x14000321600, {0x104b85e40, 0x104c815d8}, {0x0, 0x0}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:416 +0x198
github.com/daveshanley/vacuum/functions/openapi.checkExampleAsync(0x0?, 0x0?, {0x14000296400?, 0x0?}, 0x0?, {0x140003d0030, 0x14000321600, {0x104b85e40, 0x104c815d8}, {0x0, ...}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:32 +0x90
created by github.com/daveshanley/vacuum/functions/openapi.Examples.RunRule
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:145 +0x2b0
```

**Comment by daveshanley** [comment]
Hi, it's a bug - but it would be very helpful to see what caused it. Would you be able to provide a link to the spec?

**Comment by kallioaleksi** [comment]
The spec is still in development, but I managed to narrow it down. I had a typo in a `$ref` AND two examples with different bodies, and the combination of a missing definition and multiple examples causes the error.

```openapi
openapi: 3.0.3
info:
  title: Demo
  description: Demo for Vacuum segfault
  version: 1.0.0
servers:
  - url: http://localhost
paths:
  /reset:
    post:
      summary: Shortened example of a segfaulting OpenAPI spec
      requestBody:
        required: true
        content:
          application/json:
            examples:
              reset:
                summary: Example 1
                value:
                  email: demo@address.com
              change:
                summary: Example 2
                value:
                  hash: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
                  password: trustno1
            schema:
              $ref: '#/components/schemas/Reset'
      responses:
        '200':
          description: OK
```

**Comment by daveshanley** [comment]
So this was being caused deeper in the stack. I've cleaned up a few things and validated that it's no longer crashing in cases like this, where the schema cannot be found/resolved.

Can you try `v0.2.4`?

**Comment by daveshanley** [comment]
I cannot replicate this anymore, considering fixed.
