### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gnuletik** [daveshanley/vacuum#460]
Hello,

We got the following `panic` in one of our CI.
The strange thing is that this occurred only once. It was fixed after a retry.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14fafc9]

goroutine 5661 [running]:
github.com/daveshanley/vacuum/functions/openapi.DescriptionDuplication.RunRule({}, {0xc000d140a8?, 0x1b63a20?, 0x1?}, {0xc0018621e0, 0xc000478540, {0x1b37020, 0x20ab3a0}, {0x0, 0x0}, ...})
	/home/actions-runner-1/.cache/pre-commit/repojvpy7jiz/functions/openapi/description_duplication.go:59 +0x2c9
github.com/daveshanley/vacuum/motor.buildResults({0xc000478540, 0xc000122140, 0xc000122140, {0x20b9960, 0xc000126000}, 0xc000138018, 0xc000d32300, 0xc0002fc508, 0xc000146000, 0x0, ...}, ...)
	/home/actions-runner-1/.cache/pre-commit/repojvpy7jiz/motor/rule_applicator.go:827 +0x669
github.com/daveshanley/vacuum/motor.runRule({0xc000478540, 0xc000122140, 0xc000122140, {0x20b9960, 0xc000126000}, 0xc000138018, 0xc000d32300, 0xc0002fc508, 0xc000146000, 0x0, ...}, ...)
	/home/actions-runner-1/.cache/pre-commit/repojvpy7jiz/motor/rule_applicator.go:749 +0xbd6
created by github.com/daveshanley/vacuum/motor.ApplyRulesToRuleSet.func7 in goroutine 5787
	/home/actions-runner-1/.cache/pre-commit/repojvpy7jiz/motor/rule_applicator.go:605 +0x2a8
```

**Comment by daveshanley** [comment]
strange, I have no idea it would fail a single time, however I can prevent it from happening again with a nil pointer check here.

**Comment by daveshanley** [comment]
in `v0.9.8` there is a nil pointer check added to stop this from being able to fire.
