### ISSUE TITLE
`vacuum report` on stdin causes SIGSEGV

### ISSUE THREAD

**Issue by btiernay** [daveshanley/vacuum#567]
The following command:
```sh
echo '{}' | vacuum report -i
```
results in:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x1013c3384]

goroutine 1 [running]:
github.com/daveshanley/vacuum/model.(*RuleResultSet).PrepareForSerialization(0x14000526000, 0x0)
	/home/runner/work/vacuum/vacuum/model/results.go:353 +0x44
github.com/daveshanley/vacuum/cmd.GetVacuumReportCommand.func2(0x1400048a908, {0x1400045cdd0, 0x0, 0x101b0a390?})
	/home/runner/work/vacuum/vacuum/cmd/vacuum_report.go:211 +0x11d8
github.com/spf13/cobra.(*Command).execute(0x1400048a908, {0x1400045cdb0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x1400048a308)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/daveshanley/vacuum/cmd.Execute({0x101d6e260?, 0x19?}, {0x101d6ed80?, 0x101b6c4ee?}, {0x140004868c0?, 0x140000021c0?})
	/home/runner/work/vacuum/vacuum/cmd/root.go:30 +0x9c
main.main()
	/home/runner/work/vacuum/vacuum/vacuum.go:25 +0x184
```

While this does not:
```sh
echo "openapi: 3.0.1" | vacuum report -i -o
```
```
{
    "generated": "2024-10-10T08:54:14.656062-04:00",
    "specInfo": {
        "type": "openapi",
        "numLines": 2,
...
```

As an aside, this causes an issue as well:
```sh
 echo "openapi: 3.0.1" | vacuum report -i
```
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/daveshanley/vacuum/cmd.GetVacuumReportCommand.func2(0x1400048e908, {0x14000460e30, 0x0, 0x1056a6390?})
	/home/runner/work/vacuum/vacuum/cmd/vacuum_report.go:266 +0x1644
github.com/spf13/cobra.(*Command).execute(0x1400048e908, {0x14000460e10, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x1400048e308)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/daveshanley/vacuum/cmd.Execute({0x10590a260?, 0x19?}, {0x10590ad80?, 0x1057084ee?}, {0x140004888a0?, 0x140000021c0?})
	/home/runner/work/vacuum/vacuum/cmd/root.go:30 +0x9c
main.main()
	/home/runner/work/vacuum/vacuum/vacuum.go:25 +0x184
```

**Comment by daveshanley** [comment]
This has been fixed in `v0.14.2`
