### ISSUE TITLE
Can't run OWASP ruleset unless OpenAPI spec has a components property

### ISSUE THREAD

**Issue by TheTeaCat** [daveshanley/vacuum#580]
Hey,

When I run vacuum as follows I get a nil pointer dereference in the `JWTBestPractice` because there's no `components` property in my appspec, which should be fine - it's not marked as required in the OpenAPI specification.

Most appspecs worth running vacuum on probably have a `components` property, so this doesn't seem too important. Just came across it while investigating something else.

```
vacuum spectral-report -r owasp-rules.yaml my-openapi-spec.yaml spectral.json
```

<details>
<summary>Vacuum Output</summary>

```


██╗   ██╗ █████╗  ██████╗██╗   ██╗██╗   ██╗███╗   ███╗
██║   ██║██╔══██╗██╔════╝██║   ██║██║   ██║████╗ ████║
██║   ██║███████║██║     ██║   ██║██║   ██║██╔████╔██║
╚██╗ ██╔╝██╔══██║██║     ██║   ██║██║   ██║██║╚██╔╝██║
 ╚████╔╝ ██║  ██║╚██████╗╚██████╔╝╚██████╔╝██║ ╚═╝ ██║
  ╚═══╝  ╚═╝  ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝


version: latest | compiled: Fri, 15 Nov 2024 16:18:45 GMT
🔗 https://quobix.com/vacuum | https://github.com/daveshanley/vacuum


 INFO  Linting against 67 rules: https://quobix.com/vacuum/rulesets/recommended
 INFO  ❌❌❌❌❌ Context:%!(EXTRA model.RuleFunctionContext={0x1400029cc90 0x14000195380 $ <nil> 0x140001568f0 0x140001c6000 0x140004f3b40 0x140004c6000 0x14000693260})panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x1054443f8]

goroutine 213 [running]:
github.com/daveshanley/vacuum/functions/owasp.JWTBestPractice.RunRule({}, {0x30?, 0x105d9fda0?, 0x7a00014000467978?}, {0x1400029cc90, 0x14000195380, {0x105c70e20, 0x105f042f0}, {0x0, 0x0}, ...})
        /Users/josh/Documents/firetail-event-system-processor/vacuum/firetail-rules/vacuum/functions/owasp/jwt_best_practice.go:34 +0xa8
github.com/daveshanley/vacuum/motor.buildResults({0x14000195380, 0x14000452c80, 0x14000452c80, {0x105f114f0, 0x14000693240}, 0x14000695098, 0x1400029e480, 0x140001c6000, 0x140001568f0, 0x0, ...}, ...)
        /Users/josh/Documents/firetail-event-system-processor/vacuum/firetail-rules/vacuum/motor/rule_applicator.go:768 +0x588
github.com/daveshanley/vacuum/motor.runRule({0x14000195380, 0x14000452c80, 0x14000452c80, {0x105f114f0, 0x14000693240}, 0x14000695098, 0x1400029e480, 0x140001c6000, 0x140001568f0, 0x0, ...}, ...)
        /Users/josh/Documents/firetail-event-system-processor/vacuum/firetail-rules/vacuum/motor/rule_applicator.go:690 +0x910
created by github.com/daveshanley/vacuum/motor.ApplyRulesToRuleSet.func7 in goroutine 173
        /Users/josh/Documents/firetail-event-system-processor/vacuum/firetail-rules/vacuum/motor/rule_applicator.go:553 +0x21c
```
</details>

Here's my `owasp-rules.yaml`:

```yaml
extends: [[spectral:oas, recommended], [vacuum:owasp, all]]
```

And here's `my-openapi-spec.yaml`:

```yaml
openapi: 3.0.0
info:
  title: My OpenAPI Spec
  version: v0.0.0
paths:
  /pets:
    post:
      responses:
        200:
          description: Successfully added a pet to the store!
```

If I simply add `components: {}` like so it runs fine:

```yaml
openapi: 3.0.0
info:
  title: My OpenAPI Spec
  version: v0.0.0
paths:
  /pets:
    post:
      responses:
        200:
          description: Successfully added a pet to the store!
components: {}
```

**Comment by daveshanley** [comment]
This is a bug for sure. willfix

**Comment by daveshanley** [comment]
I cannot re-create this with `v0.14.3`, can you try again?

I am also a little confused by this because the code explicitly has protection against this. 

https://github.com/daveshanley/vacuum/blob/main/functions/owasp/jwt_best_practice.go#L36

**Comment by TheTeaCat** [comment]
Confirmed working in v0.14.3.
